### ISSUE TITLE
两次使用定位之后闪退

### ISSUE THREAD

**Issue by SXZXD** [qiuxiang/react-native-baidumap-sdk#71] opened 2018-06-06 06:43 UTC
操作代码：
Location.init ();
        Location.addLocationListener (location => {
            Geocode.reverse ({
                latitude: location.latitude,
                longitude: location.longitude,
            }).then (res => {
                console.info(res)
                PunchClock.address = res.district + res.description;
            });
        });
 Location.start ();
错误代码
Process: com.zajymanager.app, PID: 21917
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
at com.facebook.react.bridge.PromiseImpl.resolve(PromiseImpl.java:32)
atcn.qiuxiang.react.baidumap.modules.BaiduMapGeocodeModule$geoCoder$2$1.onGetReverseGeoCodeResult(BaiduMapGeocodeModule.kt:46)
at com.baidu.platform.core.b.e.a(Unknown Source)
at com.baidu.platform.base.c.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:815)
 at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:224)
at com.baidu.platform.core.b.e.a(Unknown Source)
at com.baidu.platform.base.c.run(Unknown Source)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:224)

**Comment by qiuxiang** [comment] 2018-06-06 06:47
Duplicate of #70

**Closed by qiuxiang** 2018-06-06 06:47 UTC
Labels: duplicate

**Comment by SXZXD** [comment] 2018-06-06 06:50
这个问题，好几天了，一直无法解决！求大神指点~

**Comment by qiuxiang** [comment] 2018-06-06 06:53
相同的问题不要重复发，让别人帮助之前，先说明白自己的问题。
